/**
 * The curriculum: what the tutor knows how to teach, and the specific wrong ideas it
 * knows how to look for.
 *
 * This is hand-authored, versioned data — deliberately not generated by a language
 * model. It is the stable spine the rest of the system reasons about: the learner model
 * tracks state per concept, the scheduler walks the prerequisite graph, and every
 * diagnosis the tutor makes must name a misconception from this closed set. If the model
 * could invent concepts or misconceptions, none of that would be checkable.
 */

/**
 * The competence areas the tutor covers.
 *
 * Areas group concepts for presentation and for the diagnostic's coverage checks. They
 * carry no ordering; sequencing comes from the prerequisite graph.
 */
export type Area =
  | 'fundamentals'
  | 'variables-and-types'
  | 'expressions'
  | 'conditionals'
  | 'loops'
  | 'functions'
  | 'collections'
  | 'debugging'
  | 'decomposition'
  | 'object-oriented'

/**
 * Every concept in the curriculum.
 *
 * Declared as an explicit union rather than inferred from the data so that prerequisite
 * lists, misconception mappings and any future reference to a concept are checked at
 * compile time. A typo becomes a type error instead of a runtime surprise.
 */
export type ConceptId =
  // fundamentals
  | 'program-execution'
  | 'output-with-print'
  | 'errors-and-tracebacks'
  // variables and types
  | 'variables-and-assignment'
  | 'numeric-types'
  | 'strings'
  | 'booleans'
  | 'type-conversion'
  // expressions
  | 'arithmetic-operators'
  | 'operator-precedence'
  | 'comparison-operators'
  | 'logical-operators'
  // conditionals
  | 'if-statements'
  | 'nested-conditionals'
  // loops
  | 'while-loops'
  | 'for-loops-and-range'
  | 'loop-accumulation'
  | 'loop-control'
  | 'nested-loops'
  // functions
  | 'defining-functions'
  | 'parameters-and-arguments'
  | 'return-values'
  | 'variable-scope'
  // collections
  | 'lists'
  | 'indexing-and-slicing'
  | 'list-mutation-and-aliasing'
  | 'dictionaries'
  | 'iterating-collections'
  // debugging
  | 'tracing-execution'
  | 'debugging-strategies'
  // decomposition
  | 'problem-decomposition'
  // object-oriented
  | 'classes-and-objects'
  | 'methods-and-attributes'

export interface Concept {
  readonly id: ConceptId
  /** Learner-facing name. */
  readonly title: string
  readonly area: Area
  /** One sentence, learner-facing: what this concept is, not why it matters. */
  readonly summary: string
  /**
   * Concepts that must be at least partly understood first. The scheduler never proposes
   * a concept whose prerequisites are unmet.
   */
  readonly prerequisites: readonly ConceptId[]
  /**
   * Difficulty of a typical item for this concept, on the same logit scale as learner
   * ability. Used as the default prior when an item does not declare its own.
   *
   * This is a *prior*, and it is never updated from a learner's answers — see ADR-0004.
   * Roughly: -1.5 is a first-week idea, 0 is mid-course, +1.5 is demanding for a beginner.
   */
  readonly baselineDifficulty: number
}

/**
 * Where a misconception in the catalogue comes from.
 *
 * Recorded per entry so that a later report can distinguish what is grounded in a
 * published inventory from what was included on practical grounds. It is internal
 * metadata and is never shown to a learner.
 */
export type MisconceptionSource =
  | {
      readonly kind: 'progmiscon'
      /** Identifier in the progmiscon.org inventory, e.g. "AssignCompares". */
      readonly id: string
      readonly url: string
    }
  | {
      /**
       * Included because it is a well-known difficulty in introductory Python that the
       * tutor needs to be able to name, but not yet traced to a specific catalogued
       * source in this project's evidence. Attribution is an open item in the ledger.
       */
      readonly kind: 'unattributed'
    }

export type MisconceptionId =
  // assignment and variables
  | 'assign-compares'
  | 'variables-hold-expressions'
  | 'variables-hold-objects'
  | 'assignment-copies-object'
  // expressions and booleans
  | 'comparison-with-bool-literal'
  | 'map-to-boolean-with-if'
  | 'no-short-circuit'
  | 'division-operator-confusion'
  // conditionals
  | 'conditional-is-sequence'
  | 'if-is-loop'
  // loops
  | 'range-endpoint-inclusive'
  | 'accumulator-overwritten'
  // functions
  | 'deferred-return'
  | 'return-unwinds-multiple-frames'
  | 'multiple-values-return'
  | 'print-instead-of-return'
  // collections
  | 'string-immutability-ignored'
  | 'index-starts-at-one'

export interface Misconception {
  readonly id: MisconceptionId
  /** Short internal name for logs and evidence records. */
  readonly title: string
  /** What the learner wrongly believes, stated as they would believe it. */
  readonly belief: string
  /** What is actually true. Used to shape corrective feedback. */
  readonly reality: string
  /** Concepts where this misconception typically shows up. */
  readonly relatedConcepts: readonly ConceptId[]
  readonly source: MisconceptionSource
}
